=== genesiscommunitysuccess/pbc/genesis-create-templates/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "title": "Genesis Create template catalog",
    "description": "Schema to define where public Genesis Create templates can be found.",
    "items": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "The unique name of the application, required for identification. Example: 'ALM - Asset Liability Management'",
          "minLength": 10,
          "maxLength": 50
        },
        "description": {
          "type": "string",
          "description": "A detailed description of the application's functionality and features. This includes information on trading features, currency movement tracking, and integrations.",
          "minLength": 100,
          "maxLength": 1000
        },
        "repo": {
          "type": "string",
          "description": "The repository where the application is stored, required. Example format: 'username/repository-name'",
          "minLength": 20
        },
        "branch": {
          "type": "string",
          "description": "The branch in the repository from which the application should be fetched. Optional, defaults to 'master' if not specified.",
          "default": "master"
        },
        "fileLocation": {
          "type": "string",
          "description": "Optional path to the configuration file within the repository.",
          "default": ".genx/genesis-create.json"
        }
      },
      "required": ["name", "repo", "description"],
      "additionalProperties": false
    }
  }

=== genesiscommunitysuccess/pbc/genesis-create-templates/catalog.json
[
    {
        "name": "ALM - Asset Liability Management",
        "description": "The Asset Liability Management application covers the booking, amendment and cancellation of FX Cash trades.",
        "repo": "genesiscommunitysuccess/alm-app",
        "branch": "master", 
        "fileLocation": ".genx/genesis.create.json"
    },
    {
        "name": "HowTo - Kafka Pipelines",
        "description": "This application has been designed to demonstrate how Kafka can be used to either poll OR publish to a kafka topic. Two pipelines have been constructed to demonstrate these use cases. The first pipeline is sourced by an event handler and uses the data from the event to publish to a kafka topic. The second pipeline then reads from this kafka topic and inserts it into the database. We have split these pipelines into 2 different scripts so that they can be run by 2 separate processes.",
        "repo": "genesiscommunitysuccess/howto-kafka-pipelines",
        "branch": "main"
    },
    {
        "name": "HowTo - Permissions",
        "description": "This application is designed to demonstrate the capabilities of the authorisation modules within Genesis. It is set up to be as simple as possible, focussing on only the authorisation elements.",
        "repo": "genesiscommunitysuccess/howto-permissions",
        "branch": "main"
    } 
]
